version: '2.1'

services:
  localstack:
    image: localstack/localstack:0.14.2
    environment:
      - SERVICES=s3,kms
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"

  metadata:
    image: amazon/amazon-ec2-metadata-mock:v1.9.2
    ports:
      - "1338:1338"
